import argparse
import numpy as np
import xarray as xr
import sparselt.esmf
import sparselt.xr
from base_state import basic_state_generator, basic_state_generator_gfdl, basic_state_generator_gfdl_shift

res_path = './' + 'RESTART/'
cache_path = './' + 'CACHE/'

#read from input
parser = argparse.ArgumentParser(description="Process variables with perturbation and shift.")
parser.add_argument('--IsPerturbation', action='store_true', help="Set this flag if perturbation is applied.")
parser.add_argument('--Shift', type=float, required=True, help="Shift value for phi.")
args = parser.parse_args()

IsPerturbation = args.IsPerturbation
Shift = args.Shift

ds_list = []
for i in range(1, 7):
    ds_tile = xr.open_dataset(res_path + f'fv_core.res.tile{i}.nc', decode_times=False)
    ds_tile = ds_tile.assign_coords({'tile': i - 1})
    ds_list.append(ds_tile)

ds = xr.concat(ds_list, dim='tile')
# ds.load()  # Optionally remove if not needed

variable_list = ['ua', 'va', 'W', 'DZ', 'T', 'phis']

base_state_generator = basic_state_generator_gfdl_shift(phi_shift=Shift)

# Load the transforms once outside the function
transform_to_180x360 = sparselt.esmf.load_weights(
    cache_path + '/c96_to_1800x3600_weights.nc',  # Generated by ESMF_RegridWeightGen
    input_dims=[('tile', 'yaxis_2', 'xaxis_1'), (6, 96, 96)],  # Applied along input dimensions
    output_dims=[('lat', 'lon'), (1800, 3600)],  # Result dimensions
)

transform_to_c96 = sparselt.esmf.load_weights(
    cache_path + '/1800x3600_to_c96_weights.nc',  # Generated by ESMF_RegridWeightGen
    input_dims=[('lat', 'lon'), (1800, 3600)],  # Applied along input dimensions
    output_dims=[('tile', 'yaxis_2', 'xaxis_1'), (6, 96, 96)],  # Result dimensions
)
'''
eta_level_original = np.array([
            0.00100, 0.00400, 0.00818, 0.01379, 0.02091,
            0.02983, 0.04121, 0.05579, 0.07420, 0.09704,
            0.12497, 0.15854, 0.19839, 0.24503, 0.29889,
            0.36004, 0.42745, 0.49824, 0.56822, 0.63383,
            0.69326, 0.74599, 0.79209, 0.83192, 0.86597,
            0.89487, 0.91922, 0.93963, 0.95667, 0.97082,
            0.98257, 0.99223, 1.00000
        ], dtype=np.float32)
'''
akbk = xr.open_dataset('./RESTART/fv_core.res.nc')
eta_level_original = np.array((akbk['ak']*1e-5+akbk['bk']).values).squeeze()
akbk.close()
def generate_ua_for_one_eta(
    input_nc_path_c96: str,
    eta_val: float,
    eta_t: float,
    phi_shift: float = 0,
    u0: float = 35.0,
    IsPerturbation = False
) -> np.ndarray:

    # Read c96 files
    ds_c96 = xr.open_dataset(input_nc_path_c96, decode_times=False)
    lats = ds_c96['lons'].values  # (193,193)
    lons = ds_c96['lats'].values  # (193,193)
    ds_c96.close()

    lam = np.deg2rad(lats)

    phi = np.deg2rad(lons)

    eta_val = eta_val if eta_val != 0 else 1e-10
    

    eta_v = (np.pi / 2) * (eta_val - eta_t)
    cos_eta_v = np.cos(eta_v) ** (3.0/2.0)

    phi_shift = np.deg2rad(phi_shift)

    #  sin_term_north, sin_term_south
    sin_term_north = np.sin(2 * (phi - phi_shift)) ** 2
    sin_term_south = np.sin(2 * (phi + phi_shift)) ** 2


    u_2d = np.where(
        phi >= 0,
        u0 * cos_eta_v * sin_term_north,
        u0 * cos_eta_v * sin_term_south
    )
    #print(u_2d.max(), u_2d.min())

    mask_narrow = (np.abs(phi) < phi_shift)
    u_2d[mask_narrow] = 0.0
    mask_wide = (np.abs(phi) > (np.pi/2 + phi_shift))
    u_2d[mask_wide] = 0.0

    if IsPerturbation:

        phi_c = np.deg2rad(40) + phi_shift 
        lam_c = np.deg2rad(20)             
        a = 6371.229e3 
        up = 1.0       
        R = a/10  

        # ------------------------------------------------
        #    argument = sin(phi_c)*sin(phi) + cos(phi_c)*cos(phi)*cos(lam - lam_c)
        # ------------------------------------------------
        argument = (np.sin(phi_c) * np.sin(phi) +
                    np.cos(phi_c) * np.cos(phi) * np.cos(lam - lam_c))
        argument = np.clip(argument, -1.0, 1.0)   
        r = a * np.arccos(argument)               

        #  u_perturb = up * exp(- (r / R)^2 )
        u_perturb = up * np.exp(-(r / R) ** 2)

        # 叠加到原始风场
        u_2d += u_perturb

    # 从 (193,193) -> (96,96) - [1:193:2, 1:193:2]
    ua_2d = u_2d[1:193:2, 1:193:2]  # shape (96,96)

    #print(ua_2d)

    return ua_2d

def generate_ua_all_eta(
    input_nc_path_c96: str,
    eta_level_original: np.ndarray,
    phi_shift: float = 0,
    u0: float = 35.0,
    IsPerturbation = False
) -> xr.DataArray:

    ua_3d_list = []


    for eta_val in eta_level_original:

        ua_2d = generate_ua_for_one_eta(
            input_nc_path_c96=input_nc_path_c96,
            eta_val=eta_val,
            eta_t=0.252,
            phi_shift=phi_shift,
            u0=u0,
            IsPerturbation=IsPerturbation
        )
        # ua_2d shape (96,96)，放到列表
        ua_3d_list.append(ua_2d[np.newaxis, :, :])  # shape (1,96,96)

    ua_3d = np.concatenate(ua_3d_list, axis=0)

    nlev = ua_3d.shape[0]  # 等于 len(eta_level_original)


    # build DataArray
    da_ua_3d = xr.DataArray(
        data=ua_3d,  # shape (nlev,96,96)
        dims=("z", "y", "x"),
        coords={
            "z": eta_level_original,
            "y": np.arange(96),
            "x": np.arange(96)
        },
        name="ua"
    )
    da_ua_3d.attrs["description"] = "zonal wind for all eta levels"
    da_ua_3d.attrs["units"] = "m/s"


    da_ua_4d = da_ua_3d.expand_dims(dim={"time": [1.0]})
    # shape (time=1, z=nlev, y=96, x=96)


    # da_ua_4d = da_ua_4d.transpose("time","z","y","x") =

    return da_ua_4d


def process_variables(dataset, variable_list, base_state_generator:basic_state_generator_gfdl_shift, IsPerturbation):
    print("Starting to process variables: {}".format(variable_list))

    # Dictionary to store the modified variables
    modified_vars = {}

    for var_target in variable_list:
        print(f"Processing variable: {var_target}")

        # Add noise to the variable data, actually i don't want noise
        temp = dataset[var_target]
        temp_np_with_noise = temp.values #+ np.random.normal(0, 0.01, size=temp.shape) 
        temp.values = temp_np_with_noise  # Use .values instead of .data

        # Transform to 180x360 grid
        ds_new = sparselt.xr.apply(transform_to_180x360, temp.to_dataset())

        # Generate new data based on the variable
        if var_target == 'ua':
            generated_data = base_state_generator.generate_zonal_u(IsPerturbation=IsPerturbation)
        elif var_target == 'va':
            generated_data = base_state_generator.generate_meridional_v()
            #print(generated_data)
        elif var_target == 'W':
            generated_data = base_state_generator.generate_vertical_w()
        elif var_target == 'DZ':
            generated_data = base_state_generator.generate_DZ()
        elif var_target == 'T':
            generated_data = base_state_generator.generate_T_v()  # Dry case
        elif var_target == 'phis':
            generated_data = base_state_generator.generate_phis()
        else:
            raise KeyError(f"Variable {var_target} not recognized.")

        # Ensure generated_data is an xarray DataArray with matching dimensions
        if not isinstance(generated_data, xr.DataArray):
            generated_data = xr.DataArray(
                generated_data,
                coords=ds_new[var_target].coords,
                dims=ds_new[var_target].dims
            )

        # Replace data in the transformed dataset
        ds_new[var_target] = generated_data

        # Transform back to c96 grid
        ds_newx = sparselt.xr.apply(transform_to_c96, ds_new[var_target].to_dataset())

        # Store the modified variable data
        modified_vars[var_target] = ds_newx[var_target]

    # After all variables are processed, write them back to the tile files
    print("All variables processed. Now saving to files.")

    for i in range(1, 7):
        # Open the tile dataset once and modify all variables
        ds_temp = xr.open_dataset(res_path + f'fv_core.res.tile{i}.nc', decode_times=False)

        for var_target in variable_list:
            if (var_target in ds_temp):
                # Extract the data for the current tile
                modified_data = modified_vars[var_target].isel(tile=i-1)

                # Align dimensions to match ds_temp[var_target]
                modified_data = modified_data.transpose(*ds_temp[var_target].dims)

                # Assign the modified data to the dataset
                ds_temp[var_target].values = modified_data.values
                #print(var_target)
            #elif var_target == 'phis':
            #    print('dealing with phis')




            else:
                print(f"Variable {var_target} not found in tile {i}. Skipping.")
        print('Renerate ua...')
        ua_4d = generate_ua_all_eta(
            input_nc_path_c96=cache_path + f'c96.tile{i}.nc',
            eta_level_original=0.5 * (eta_level_original[1:] + eta_level_original[:-1]),
            phi_shift=Shift,
            u0=35.0,
            IsPerturbation = IsPerturbation
        )
        if 'ua' in ds_temp.data_vars:
            ds_temp['ua'].values = ua_4d.values
            
            ds_temp['u'].values = np.zeros_like(ds_temp['u'].values)
            ds_temp['v'].values = np.zeros_like(ds_temp['v'].values)
            ds_temp['u0'].values = np.zeros_like(ds_temp['u0'].values)
            ds_temp['v0'].values = np.zeros_like(ds_temp['v0'].values)

            print('Others has been set to 0.')

        if 'T' in ds_temp.data_vars:
            print('Converting T_v to T')
            ds_c96 = xr.open_dataset('./CACHE/c96.tile{}.nc'.format(i), decode_times=False)
            lons = ds_c96['lons'].values  # (193,193)
            lats = ds_c96['lats'].values  # (193,193)
            ds_c96.close()

            delp = ds_temp['delp'].values #z,y,x
            pe = np.zeros((33,96,96))
            pe[0,:,:] = 100
            for idx in range(32):
                #print(delp)
                pe[idx+1,:,:] = pe[idx,:,:]+delp[0,idx,:,:]

            peln = np.log(pe)

            ptmp = delp[0,:,:,:] / (peln[1:,:,:] - peln[:-1,:,:]) - 1e5#32,96,06


            temp_radius = 2/9 * np.pi #+ np.deg2rad(Shift)

            phi = np.deg2rad(lats)[1:193:2, 1:193:2]

            phi = phi[np.newaxis, :, :]#1,96,96

            q = 0.021 * np.exp(-(phi/temp_radius)**4)*np.exp(-(ptmp/34000)**2)

            q = q[np.newaxis,:,:,:]

            #print(q)

            ds_temp = ds_temp.assign(T=ds_temp['T'] / (1 + 0.608 * q))
        
        # Save the modified dataset
        ds_temp.to_netcdf(cache_path + f'fv_core.res.tile{i}.nc')
        ds_temp.close()

    print("All files have been saved successfully.")

process_variables(ds, variable_list, base_state_generator, IsPerturbation=IsPerturbation)