import argparse
import numpy as np
import xarray as xr
import sparselt.esmf
import sparselt.xr
from base_state import basic_state_generator, basic_state_generator_gfdl, basic_state_generator_gfdl_shift
import os

res_path = './' + 'RESTART/'
cache_path = './' + 'CACHE/'

#read from input
parser = argparse.ArgumentParser(description="Process variables with perturbation and shift.")
parser.add_argument('--IsPerturbation', action='store_true', help="Set this flag if perturbation is applied.")
parser.add_argument('--Shift', type=float, default = 0, help="Shift value for phi.")
parser.add_argument('--b', type=float, default = 2.0, help="b, depth of the western jet, or wind shear")
parser.add_argument('--n', type=float, default = 1.0, help="Width of he western jet.")
parser.add_argument('--gamma', type=float, default = 5e-3, help="lapse rate")
parser.add_argument('--phi_c', type=float, default = 40, help="latitude center of perturbation")
parser.add_argument('--RH0', type=float, default = 0.8, help="Surface relative humidity")
args = parser.parse_args()

IsPerturbation = args.IsPerturbation
Shift = args.Shift
b = args.b
n = args.n
gamma = args.gamma
phi_c = args.phi_c
RH0 = args.RH0


ds_list = []
for i in range(1, 7):
    ds_tile = xr.open_dataset(res_path + f'fv_core.res.tile{i}.nc', decode_times=False)
    ds_tile = ds_tile.assign_coords({'tile': i - 1})
    ds_list.append(ds_tile)

ds = xr.concat(ds_list, dim='tile')
# ds.load()  # Optionally remove if not needed

variable_list = ['ua', 'va', 'W', 'DZ', 'T', 'phis']

base_state_generator = basic_state_generator_gfdl_shift(phi_shift=Shift, 
b=b, n=n, gamma=gamma,phi_c=phi_c)

# Load the transforms once outside the function
transform_to_180x360 = sparselt.esmf.load_weights(
    cache_path + '/c96_to_1800x3600_weights.nc',  # Generated by ESMF_RegridWeightGen
    input_dims=[('tile', 'yaxis_2', 'xaxis_1'), (6, 96, 96)],  # Applied along input dimensions
    output_dims=[('lat', 'lon'), (1800, 3600)],  # Result dimensions
)

transform_to_c96 = sparselt.esmf.load_weights(
    cache_path + '/1800x3600_to_c96_weights.nc',  # Generated by ESMF_RegridWeightGen
    input_dims=[('lat', 'lon'), (1800, 3600)],  # Applied along input dimensions
    output_dims=[('tile', 'yaxis_2', 'xaxis_1'), (6, 96, 96)],  # Result dimensions
)
'''
eta_level_original = np.array([
            0.00100, 0.00400, 0.00818, 0.01379, 0.02091,
            0.02983, 0.04121, 0.05579, 0.07420, 0.09704,
            0.12497, 0.15854, 0.19839, 0.24503, 0.29889,
            0.36004, 0.42745, 0.49824, 0.56822, 0.63383,
            0.69326, 0.74599, 0.79209, 0.83192, 0.86597,
            0.89487, 0.91922, 0.93963, 0.95667, 0.97082,
            0.98257, 0.99223, 1.00000
        ], dtype=np.float32)
'''
akbk = xr.open_dataset('./RESTART/fv_core.res.nc')
eta_level_original = np.array((akbk['ak']*1e-5+akbk['bk']).values).squeeze()
akbk.close()

def RH_profile(eta, RH0):
    eta = np.asarray(eta)
    RH = np.zeros_like(eta, dtype=float)

    m1 = (eta >= 0.0) & (eta < 0.1)
    m2 = (eta >= 0.1) & (eta < 0.3)
    m3 = (eta >= 0.3) & (eta <= 0.8)
    m4 = (eta > 0.8)

    RH[m1] = 0.0
    RH[m2] = (3.5 * eta[m2] - 0.35) * RH0
    RH[m3] = 0.7 * RH0
    RH[m4] = (1.5 * eta[m4] - 0.5) * RH0

    return RH


def es(T):
    return 611.21 * np.exp(17.67 * (T - 273.15) / (T - 29.65))


def q_from_es_RH(es_vals, RH, p):
    eps = 0.622
    return eps * RH * es_vals / (p - (1 - eps) * RH * es_vals)


def compute_q_T_iterative(T_v, RH0, eta, tol=0.001, max_iter=10):
    """
    T_v:  (time, nlev, y, x)
    RH0:  scalar or (nlev,)
    eta:  1D array of length nlev (mid-level)
    """
    T_v = np.asarray(T_v)
    nt, nz, ny, nx = T_v.shape


    RH1d = RH_profile(eta, RH0)              # (nz,)
    RH  = RH1d[None, :, None, None]          # (1,nz,1,1)


    p_mid = eta * 1e5                        # (nz,)
    p     = p_mid[None, :, None, None]       # (1,nz,1,1)

    T     = T_v.copy()
    q_old = np.zeros_like(T)
    for _ in range(max_iter):
        es_vals = es(T)                      # (1,nz,ny,nx)

        q_new = q_from_es_RH(es_vals, RH, p)
        T     = T_v / (1 + 0.608 * q_new)

        denom    = np.maximum(np.abs(q_old), np.abs(q_new))
        denom[denom==0] = 1.0
        rel_diff = np.abs(q_new - q_old)/denom
        if np.nanmax(rel_diff) < tol:
            break
        q_old = q_new.copy()

        #print(T/T_v)

        print('interative T and q finished.')

    return q_new, T


def process_variables(dataset, variable_list, base_state_generator:basic_state_generator_gfdl_shift, IsPerturbation):
    print("Starting to process variables: {}".format(variable_list))

    # Dictionary to store the modified variables
    modified_vars = {}

    for var_target in variable_list:
        print(f"Processing variable: {var_target}")

        # Add noise to the variable data, actually i don't want noise
        temp = dataset[var_target]
        temp_np_with_noise = temp.values #+ np.random.normal(0, 0.01, size=temp.shape) 
        temp.values = temp_np_with_noise  # Use .values instead of .data

        # Transform to 180x360 grid
        ds_new = sparselt.xr.apply(transform_to_180x360, temp.to_dataset())

        # Generate new data based on the variable
        if var_target == 'ua':
            generated_data = base_state_generator.generate_zonal_u(IsPerturbation=IsPerturbation)
        elif var_target == 'va':
            generated_data = base_state_generator.generate_meridional_v()
            #print(generated_data)
        elif var_target == 'W':
            generated_data = base_state_generator.generate_vertical_w()
        elif var_target == 'DZ':
            generated_data = base_state_generator.generate_DZ()
        elif var_target == 'T':
            generated_data = base_state_generator.generate_T_v()  # Dry case
        elif var_target == 'phis':
            generated_data = base_state_generator.generate_phis()
        else:
            raise KeyError(f"Variable {var_target} not recognized.")

        # Ensure generated_data is an xarray DataArray with matching dimensions
        if not isinstance(generated_data, xr.DataArray):
            generated_data = xr.DataArray(
                generated_data,
                coords=ds_new[var_target].coords,
                dims=ds_new[var_target].dims
            )

        # Replace data in the transformed dataset
        ds_new[var_target] = generated_data

        # Transform back to c96 grid
        ds_newx = sparselt.xr.apply(transform_to_c96, ds_new[var_target].to_dataset())

        # Store the modified variable data
        modified_vars[var_target] = ds_newx[var_target]

    # After all variables are processed, write them back to the tile files
    print("All variables processed. Now saving to files.")

    for i in range(1, 7):
        # Open the tile dataset once and modify all variables
        ds_temp = xr.open_dataset(res_path + f'fv_core.res.tile{i}.nc', decode_times=False)
        
        ds_srf = xr.open_dataset(
        res_path + f'fv_tracer.res.tile{i}.nc',
        decode_times=False
        )
        for var_target in variable_list:
            if (var_target in ds_temp):
                # Extract the data for the current tile
                modified_data = modified_vars[var_target].isel(tile=i-1)

                # Align dimensions to match ds_temp[var_target]
                modified_data = modified_data.transpose(*ds_temp[var_target].dims)

                # Assign the modified data to the dataset
                ds_temp[var_target].values = modified_data.values
                #print(var_target)
            #elif var_target == 'phis':
            #    print('dealing with phis')

            else:
                print(f"Variable {var_target} not found in tile {i}. Skipping.")
        

        if 'T' in ds_temp.data_vars:
            print('Converting T_v to T')
            ds_c96 = xr.open_dataset('./CACHE/c96.tile{}.nc'.format(i), decode_times=False)
            lons = ds_c96['lons'].values  # (193,193)
            lats = ds_c96['lats'].values  # (193,193)
            ds_c96.close()

            delp = ds_temp['delp'].values #z,y,x
            eta = 0.5*(eta_level_original[:-1] + eta_level_original[1:])
            q_finished, T_finished = compute_q_T_iterative(ds_temp['T'].values, RH0, eta)
            print(q_finished.shape)
            '''
            pe = np.zeros((33,96,96))
            pe[0,:,:] = 100
            for idx in range(32):
                #print(delp)
                pe[idx+1,:,:] = pe[idx,:,:]+delp[0,idx,:,:]

            peln = np.log(pe)

            ptmp = delp[0,:,:,:] / (peln[1:,:,:] - peln[:-1,:,:]) - 1e5#32,96,06


            temp_radius = 2/9 * np.pi #+ np.deg2rad(Shift)

            phi = np.deg2rad(lats)[1:193:2, 1:193:2]

            phi = phi[np.newaxis, :, :]#1,96,96

            q = 0.021 * np.exp(-(phi/temp_radius)**4)*np.exp(-(ptmp/34000)**2)

            q = q[np.newaxis,:,:,:]

            #print(q)
            '''
            ds_temp['T'].values = T_finished

            print('Converting T.')
        
        
        if 'sphum' in ds_srf.data_vars:
            ds_srf['sphum'].values = q_finished
            print('Converting q.')
        else:
            print(f"[Warning] tile{i} skipped")

        out_name = cache_path + f'fv_tracer.res.tile{i}.nc'
        ds_srf.to_netcdf(out_name)
        ds_srf.close()
        print(f"Saved surface restart tile {i} → {out_name}")
        
        # Save the modified dataset
        ds_temp.to_netcdf(cache_path + f'fv_core.res.tile{i}.nc')
        ds_temp.close()

    print("All files have been saved successfully.")


process_variables(ds, variable_list, base_state_generator, IsPerturbation=IsPerturbation)