import argparse
import numpy as np
import xarray as xr
import sparselt.esmf
import sparselt.xr
from base_state import basic_state_generator, basic_state_generator_gfdl, basic_state_generator_gfdl_shift

res_path = './' + 'RESTART/'
cache_path = './' + 'CACHE/'

#read from input
parser = argparse.ArgumentParser(description="Process variables with perturbation and shift.")
parser.add_argument('--IsPerturbation', action='store_true', help="Set this flag if perturbation is applied.")
parser.add_argument('--Shift', type=float, required=True, help="Shift value for phi.")
args = parser.parse_args()

IsPerturbation = args.IsPerturbation
Shift = args.Shift

ds_list = []
for i in range(1, 7):
    ds_tile = xr.open_dataset(res_path + f'fv_core.res.tile{i}.nc', decode_times=False)
    ds_tile = ds_tile.assign_coords({'tile': i - 1})
    ds_list.append(ds_tile)

ds = xr.concat(ds_list, dim='tile')
# ds.load()  # Optionally remove if not needed

variable_list = ['ua', 'va', 'W', 'DZ', 'T']

base_state_generator = basic_state_generator_gfdl_shift(phi_shift=Shift)

# Load the transforms once outside the function
transform_to_180x360 = sparselt.esmf.load_weights(
    cache_path + '/c96_to_180x360_weights.nc',  # Generated by ESMF_RegridWeightGen
    input_dims=[('tile', 'yaxis_2', 'xaxis_1'), (6, 96, 96)],  # Applied along input dimensions
    output_dims=[('lat', 'lon'), (180, 360)],  # Result dimensions
)

transform_to_c96 = sparselt.esmf.load_weights(
    cache_path + '/180x360_to_c96_weights.nc',  # Generated by ESMF_RegridWeightGen
    input_dims=[('lat', 'lon'), (180, 360)],  # Applied along input dimensions
    output_dims=[('tile', 'yaxis_2', 'xaxis_1'), (6, 96, 96)],  # Result dimensions
)

def process_variables(dataset, variable_list, base_state_generator:basic_state_generator_gfdl_shift, IsPerturbation):
    print("Starting to process variables: {}".format(variable_list))

    # Dictionary to store the modified variables
    modified_vars = {}

    for var_target in variable_list:
        print(f"Processing variable: {var_target}")

        # Add noise to the variable data, actually i don't want noise
        temp = dataset[var_target]
        temp_np_with_noise = temp.values #+ np.random.normal(0, 0.01, size=temp.shape) 
        temp.values = temp_np_with_noise  # Use .values instead of .data

        # Transform to 180x360 grid
        ds_new = sparselt.xr.apply(transform_to_180x360, temp.to_dataset())

        # Generate new data based on the variable
        if var_target == 'ua':
            generated_data = base_state_generator.generate_zonal_u(IsPerturbation=IsPerturbation)
        elif var_target == 'va':
            generated_data = base_state_generator.generate_meridional_v()
            #print(generated_data)
        elif var_target == 'W':
            generated_data = base_state_generator.generate_vertical_w()
        elif var_target == 'DZ':
            generated_data = base_state_generator.generate_DZ()
        elif var_target == 'T':
            generated_data = base_state_generator.generate_T_v()  # Dry case
        elif var_target == 'phis':
            generated_data = base_state_generator.generate_phis()
        else:
            raise KeyError(f"Variable {var_target} not recognized.")

        # Ensure generated_data is an xarray DataArray with matching dimensions
        if not isinstance(generated_data, xr.DataArray):
            generated_data = xr.DataArray(
                generated_data,
                coords=ds_new[var_target].coords,
                dims=ds_new[var_target].dims
            )

        # Replace data in the transformed dataset
        ds_new[var_target] = generated_data

        # Transform back to c96 grid
        ds_newx = sparselt.xr.apply(transform_to_c96, ds_new[var_target].to_dataset())

        # Store the modified variable data
        modified_vars[var_target] = ds_newx[var_target]

    # After all variables are processed, write them back to the tile files
    print("All variables processed. Now saving to files.")

    for i in range(1, 7):
        # Open the tile dataset once and modify all variables
        ds_temp = xr.open_dataset(res_path + f'fv_core.res.tile{i}.nc', decode_times=False)

        for var_target in variable_list:
            if var_target in ds_temp:
                # Extract the data for the current tile
                modified_data = modified_vars[var_target].isel(tile=i-1)

                # Align dimensions to match ds_temp[var_target]
                modified_data = modified_data.transpose(*ds_temp[var_target].dims)

                # Assign the modified data to the dataset
                ds_temp[var_target].values = modified_data.values
            else:
                print(f"Variable {var_target} not found in tile {i}. Skipping.")

        # Save the modified dataset
        ds_temp.to_netcdf(cache_path + f'fv_core.res.tile{i}.nc')
        ds_temp.close()

    print("All files have been saved successfully.")

process_variables(ds, variable_list, base_state_generator, IsPerturbation=IsPerturbation)
